language: generic
os: linux
dist: bionic # Ubuntu 18.04 LTS
services:
  - docker

before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (heroku)
  - echo "$HEROKU_API_KEY" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

script:
  - set -e # exit from first failure
  - docker build -f infra/web/Dockerfile . # Test that everything builds properly
  - test/run_docker_tests.sh # run tests
  - docker-compose -f ./infra/web/docker-compose.yml -p of-arena up --no-start

deploy:
  - provider: script
    script: docker tag of-arena-web registry.heroku.com/$HEROKU_APP_DEV/web;
      docker push registry.heroku.com/$HEROKU_APP_DEV/web;
      heroku container:release web --app $HEROKU_APP_DEV
    on:
      branch: master
  - provider: script
    script: docker tag of-arena-web registry.heroku.com/$HEROKU_APP_PROD/web;
      docker push registry.heroku.com/$HEROKU_APP_PROD/web;
      heroku container:release web --app $HEROKU_APP_PROD
    on:
      tags: true
  - provider: script
    script: docker tag of-arena-web registry.heroku.com/openforis-arena-incubator/web;
      docker push registry.heroku.com/openforis-arena-incubator/web;
      heroku container:release web --app openforis-arena-incubator
    on:
      branch: incubator
